services:
  taskflaw:
    image: flyingfrares/taskflaw
    ports:
      - '8000:8000'
    container_name: taskflaw-web

  watchtower:
    image: containrrr/watchtower
    command:
      - --rolling-restart=true
      - --interval=120
      - taskflaw-web
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: taskflaw-watchtower