name: Docker Scout

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build a Docker image
        run: docker build -f Dockerfile -t flyin/taskflaw-test .

      - name: Docker Scout Scan
        uses: docker/scout-action@v1
        with:
          dockerhub-user: ${{ vars.DOCKER_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}
          command: quickview,cves,recommendations
          # fail the build if any critical or high severity vulnerabilities are found
          only-severities: critical,high
          exit-code: true
          to-latest: true
          ignore-base: true
          ignore-unchanged: true
          only-fixed: true