name: Snyk Container Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build a Docker image
        run: docker build -f Dockerfile -t flyin/taskflaw-test .

      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: 9a29ca3a-3fa6-465e-8f8d-bed4101b3c7d
        with:
          image: flyin/taskflaw-test
        # command: monitor