name: Snyk SCA Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        continue-on-error: false
        env:
          COMMAND: "pip install --upgrade pip -r requirements.txt"
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test --file=requirements.txt --severity-threshold=low
        # Send snapshot directly to app.snyk.io
        # command: monitor --file=requirements.txt
