name: Trufflehog

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Trufflehog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: TruffleHog OSS
      uses: trufflesecurity/trufflehog@v3.82.11
      with:
        base: ""
        head: ${{ github.ref_name }}