name: Trufflehog

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  Trufflehog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: TruffleHog OSS
      uses: trufflesecurity/trufflehog@v3.83.5
      with:
        base: HEAD~100 # Scan last 100 commits
      # base: "" # Scan all history
      # base: 37abccf0c3f204008f85578a49563fad690be9ae # Scan from a specific commit
        head: main